{
  description = "POAG API - OpenAPI specification and generated client/server";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";

    # Inherit Python tooling from parent poag flake
    pyproject-nix.url = "github:pyproject-nix/pyproject.nix";
    uv2nix.url = "github:pyproject-nix/uv2nix";
    pyproject-build-systems.url = "github:pyproject-nix/build-system-pkgs";
  };

  outputs = { self, nixpkgs, flake-utils, pyproject-nix, uv2nix, pyproject-build-systems }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        python = pkgs.python312;

        # OpenAPI spec
        spec = ./poag.json;

        # Load the workspace for dependency management
        workspace = uv2nix.lib.workspace.loadWorkspace {
          workspaceRoot = ./.;
        };

        overlay = workspace.mkPyprojectOverlay {
          sourcePreference = "wheel";
        };

        pythonSet = (pkgs.callPackage pyproject-nix.build.packages {
          inherit python;
        }).overrideScope (
          pkgs.lib.composeManyExtensions [
            pyproject-build-systems.overlays.default
            overlay
          ]
        );

        # Editable overlay for development
        editableOverlay = workspace.mkEditablePyprojectOverlay {
          root = "$REPO_ROOT";
        };

        editablePythonSet = pythonSet.overrideScope editableOverlay;

        # Virtual environment with all dependencies (including dev)
        apiEnv = pythonSet.mkVirtualEnv "poag-api-env" workspace.deps.default;

        # FastAPI server - generated by openapi-generator
        fastapi-server = pkgs.runCommand "poag-api-server" {
          nativeBuildInputs = [ pkgs.openapi-generator-cli ];
        } ''
          openapi-generator-cli generate \
            -i ${spec} \
            -g python-fastapi \
            -o $out \
            --package-name poag_api_server \
            --additional-properties=generateSourceCodeOnly=true
        '';

        # Python client - generated by openapi-generator
        python-client = pkgs.runCommand "poag-api-client-py" {
          nativeBuildInputs = [ pkgs.openapi-generator-cli ];
        } ''
          openapi-generator-cli generate \
            -i ${spec} \
            -g python \
            -o $out \
            --package-name poag_api_client \
            --additional-properties=generateSourceCodeOnly=true,packageVersion=0.1.0
        '';

        # TypeScript client - generated by openapi-generator
        typescript-client = pkgs.runCommand "poag-api-client-ts" {
          nativeBuildInputs = [ pkgs.openapi-generator-cli ];
        } ''
          openapi-generator-cli generate \
            -i ${spec} \
            -g typescript-fetch \
            -o $out \
            --additional-properties=npmName=@poag/api-client,npmVersion=0.1.0,supportsES6=true
        '';

        # API documentation - generated by redocly
        api-docs = pkgs.runCommand "poag-api-docs" {
          nativeBuildInputs = [ pkgs.redocly ];
        } ''
          mkdir -p $out
          redocly build-docs ${spec} -o $out/index.html
        '';

      in
      {
        packages = {
          default = apiEnv;
          server = fastapi-server;
          client-py = python-client;
          client-ts = typescript-client;
          docs = api-docs;
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            (editablePythonSet.mkVirtualEnv "poag-api-dev" workspace.deps.all)
            uv
            openapi-generator-cli
            redocly
            nix  # For running nix build commands
          ];
          env = {
            UV_NO_SYNC = "1";
            UV_PYTHON = python.interpreter;
            UV_PYTHON_DOWNLOADS = "never";
          };
          shellHook = ''
            export REPO_ROOT=$(pwd)

            echo "POAG API development environment"
            echo ""
            echo "Code generation (fully offline, happens during nix build):"
            echo "  nix build .#server         # Generate FastAPI server"
            echo "  nix build .#client-py      # Generate Python client"
            echo "  nix build .#client-ts      # Generate TypeScript client"
            echo "  nix build .#docs           # Generate API documentation"
            echo ""
            echo "Testing & validation:"
            echo "  pytest tests/ -v           # Run tests (validates generated code)"
            echo "  nix flake check            # Run all checks including pytest"
            echo ""
            echo "Workflow:"
            echo "  1. Edit poag.json (OpenAPI spec)"
            echo "  2. Run 'nix build .#<package>' to generate code"
            echo "  3. Run 'pytest' to verify generated packages"
            echo "  4. All builds are pure and reproducible"
            echo ""
            echo "Note: DevShell loads independently of code generation."
            echo "      Even if the spec has errors, you can still fix it here."
          '';
        };

        checks = {
          # Run pytest tests that verify generated packages
          pytest = pkgs.runCommand "poag-api-pytest" {
            buildInputs = [
              apiEnv
              pkgs.nix
              pkgs.cacert
            ];
          } ''
            export HOME=$TMPDIR
            export PYTHONDONTWRITEBYTECODE=1
            export NIX_CONFIG="extra-experimental-features = nix-command flakes"
            export SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt

            # Make generated packages available to tests
            export POAG_SERVER_PATH="${fastapi-server}"
            export POAG_CLIENT_PY_PATH="${python-client}"
            export POAG_CLIENT_TS_PATH="${typescript-client}"

            # Copy source files to build directory
            cp -r ${./.} ./poag-api
            chmod -R +w ./poag-api
            cd ./poag-api

            # Run pytest
            ${apiEnv}/bin/pytest tests/ -v --tb=short

            # Create output directory (required for checks)
            mkdir -p $out
            echo "All tests passed" > $out/result
          '';
        };
      }
    );
}
