{
  description = "POAG API - OpenAPI specification and generated client/server";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";

    # Inherit Python tooling from parent poag flake
    pyproject-nix.url = "github:pyproject-nix/pyproject.nix";
    uv2nix.url = "github:pyproject-nix/uv2nix";
    pyproject-build-systems.url = "github:pyproject-nix/build-system-pkgs";
  };

  outputs = { self, nixpkgs, flake-utils, pyproject-nix, uv2nix, pyproject-build-systems }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        python = pkgs.python312;

        # OpenAPI spec
        spec = ./poag.json;

        # Load the workspace for dependency management
        workspace = uv2nix.lib.workspace.loadWorkspace {
          workspaceRoot = ./.;
        };

        overlay = workspace.mkPyprojectOverlay {
          sourcePreference = "wheel";
        };

        pythonSet = (pkgs.callPackage pyproject-nix.build.packages {
          inherit python;
        }).overrideScope (
          pkgs.lib.composeManyExtensions [
            pyproject-build-systems.overlays.default
            overlay
          ]
        );

        # Editable overlay for development
        editableOverlay = workspace.mkEditablePyprojectOverlay {
          root = "$REPO_ROOT";
        };

        editablePythonSet = pythonSet.overrideScope editableOverlay;

        # Virtual environment with all dependencies (including dev)
        apiEnv = pythonSet.mkVirtualEnv "poag-api-env" workspace.deps.default;

        # FastAPI server - generated by openapi-generator
        fastapi-server = pkgs.runCommand "poag-api-server" {
          nativeBuildInputs = [ pkgs.openapi-generator-cli ];
        } ''
          openapi-generator-cli generate \
            -i ${spec} \
            -g python-fastapi \
            -o $out \
            --package-name poag_api_server \
            --additional-properties=generateSourceCodeOnly=true
        '';

        # Python client - generated by openapi-generator
        python-client = pkgs.runCommand "poag-api-client-py" {
          nativeBuildInputs = [ pkgs.openapi-generator-cli ];
        } ''
          openapi-generator-cli generate \
            -i ${spec} \
            -g python \
            -o $out \
            --package-name poag_api_client \
            --additional-properties=generateSourceCodeOnly=true,packageVersion=0.1.0
        '';

        # TypeScript client - generated by openapi-generator
        typescript-client = pkgs.runCommand "poag-api-client-ts" {
          nativeBuildInputs = [ pkgs.openapi-generator-cli ];
        } ''
          openapi-generator-cli generate \
            -i ${spec} \
            -g typescript-fetch \
            -o $out \
            --additional-properties=npmName=@poag/api-client,npmVersion=0.1.0,supportsES6=true
        '';

        # API documentation - generated by redocly
        api-docs = pkgs.runCommand "poag-api-docs" {
          nativeBuildInputs = [ pkgs.redocly ];
        } ''
          mkdir -p $out
          redocly build-docs ${spec} -o $out/index.html
        '';

        # Build Python client as an installable package
        python-client-pkg = python.pkgs.buildPythonPackage {
          pname = "poag-api-client";
          version = "0.1.0";
          format = "setuptools";

          src = python-client;

          nativeBuildInputs = with python.pkgs; [
            setuptools
            wheel
          ];

          # The generated client doesn't have a setup.py, so we create one
          preBuild = ''
            cat > setup.py << 'EOF'
from setuptools import setup, find_packages

setup(
    name="poag-api-client",
    version="0.1.0",
    description="POAG API Client",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "urllib3>=1.25.3,<3.0.0",
        "python-dateutil>=2.8.2",
        "pydantic>=2.0.0",
        "certifi>=2023.7.22",
        "six>=1.10",
    ],
)
EOF
          '';

          # Skip tests for generated code
          doCheck = false;

          pythonImportsCheck = [ "poag_api_client" ];

          # CRITICAL: mkVirtualEnv reads passthru.dependencies, not propagatedBuildInputs
          passthru = {
            dependencies = {
              pydantic = [ ];
              python-dateutil = [ ];
              urllib3 = [ ];
              certifi = [ ];
              six = [ ];
            };
            optional-dependencies = { };
          };
        };

        # Build FastAPI server as an installable package
        python-server-pkg = python.pkgs.buildPythonPackage {
          pname = "poag-api-server";
          version = "0.1.0";
          format = "setuptools";

          src = fastapi-server;

          nativeBuildInputs = with python.pkgs; [
            setuptools
            wheel
          ];

          # The generated server doesn't have a proper setup.py, so we create one
          preBuild = ''
            cat > setup.py << 'EOF'
from setuptools import setup, find_packages

setup(
    name="poag-api-server",
    version="0.1.0",
    description="POAG API Server (Generated)",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "fastapi>=0.120.0",
        "pydantic>=2.0",
        "uvicorn[standard]>=0.13.4",
        "starlette>=0.49.0",
        "python-multipart>=0.0.18",
        "PyYAML>=5.4.1",
        "aiofiles>=23.1.0",
    ],
)
EOF
          '';

          # Skip tests for generated code
          doCheck = false;

          pythonImportsCheck = [ "poag_api_server" ];

          # CRITICAL: mkVirtualEnv reads passthru.dependencies, not propagatedBuildInputs
          passthru = {
            dependencies = {
              fastapi = [ ];
              pydantic = [ ];
              uvicorn = [ ];  # Base uvicorn without extras (extras not in uv.lock)
              starlette = [ ];
              python-multipart = [ ];
              pyyaml = [ ];
              aiofiles = [ ];
            };
            optional-dependencies = { };
          };
        };

        # Create source packages with pyproject.toml for uv consumption
        client-py-source = pkgs.runCommand "poag-api-client-source" {} ''
          mkdir -p $out
          cp -r ${python-client}/* $out/
          chmod -R +w $out
          cp ${./client-pyproject.toml} $out/pyproject.toml
        '';

        server-source = pkgs.runCommand "poag-api-server-source" {} ''
          mkdir -p $out
          cp -r ${fastapi-server}/* $out/
          chmod -R +w $out
          cp ${./server-pyproject.toml} $out/pyproject.toml
        '';

      in
      {
        packages = {
          default = apiEnv;
          server = fastapi-server;
          server-pkg = python-server-pkg;
          server-source = server-source;  # For uv consumption
          client-py = python-client;
          client-py-pkg = python-client-pkg;
          client-py-source = client-py-source;  # For uv consumption
          client-ts = typescript-client;
          docs = api-docs;
        };

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            (editablePythonSet.mkVirtualEnv "poag-api-dev" workspace.deps.all)
            uv
            openapi-generator-cli
            redocly
            nix  # For running nix build commands
          ];
          env = {
            UV_NO_SYNC = "1";
            UV_PYTHON = python.interpreter;
            UV_PYTHON_DOWNLOADS = "never";
          };
          shellHook = ''
            export REPO_ROOT=$(pwd)

            echo "POAG API development environment"
            echo ""
            echo "Code generation (fully offline, happens during nix build):"
            echo "  nix build .#server         # Generate FastAPI server"
            echo "  nix build .#client-py      # Generate Python client"
            echo "  nix build .#client-ts      # Generate TypeScript client"
            echo "  nix build .#docs           # Generate API documentation"
            echo ""
            echo "Testing & validation:"
            echo "  pytest tests/ -v           # Run tests (validates generated code)"
            echo "  nix flake check            # Run all checks including pytest"
            echo ""
            echo "Workflow:"
            echo "  1. Edit poag.json (OpenAPI spec)"
            echo "  2. Run 'nix build .#<package>' to generate code"
            echo "  3. Run 'pytest' to verify generated packages"
            echo "  4. All builds are pure and reproducible"
            echo ""
            echo "Note: DevShell loads independently of code generation."
            echo "      Even if the spec has errors, you can still fix it here."
          '';
        };

        checks = {
          # Run pytest tests that verify generated packages
          pytest = pkgs.runCommand "poag-api-pytest" {
            buildInputs = [
              apiEnv
              pkgs.nix
              pkgs.cacert
            ];
          } ''
            export HOME=$TMPDIR
            export PYTHONDONTWRITEBYTECODE=1
            export NIX_CONFIG="extra-experimental-features = nix-command flakes"
            export SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt

            # Make generated packages available to tests
            export POAG_SERVER_PATH="${fastapi-server}"
            export POAG_CLIENT_PY_PATH="${python-client}"
            export POAG_CLIENT_TS_PATH="${typescript-client}"

            # Copy source files to build directory
            cp -r ${./.} ./poag-api
            chmod -R +w ./poag-api
            cd ./poag-api

            # Run pytest
            ${apiEnv}/bin/pytest tests/ -v --tb=short

            # Create output directory (required for checks)
            mkdir -p $out
            echo "All tests passed" > $out/result
          '';
        };
      }
    );
}
